# Generated by Django 2.1.7 on 2019-03-01 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=164)),
            ],
        ),
        migrations.CreateModel(
            name='Modern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modern_word', models.CharField(max_length=164)),
                ('origin_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etym.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Original',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_word', models.CharField(max_length=164)),
                ('origin_meaning', models.CharField(max_length=164)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=164)),
            ],
        ),
        migrations.AddField(
            model_name='modern',
            name='origin_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etym.Region'),
        ),
        migrations.AddField(
            model_name='modern',
            name='origin_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etym.Original'),
        ),
    ]
